;; TODO: Fix spritesheet! Accents and whatnot

slide1:
  .db $10,"      Ano de introdu",$18,$0E,"o       ",$11
  .db "                                "
  .db " 1983: Jap",$0E,"o, como ",$80,$81,$82,$83,$84,$85,$86,$87,$88,$84,$89,"  "
  .db "       (Family Computer, FC ou  "
  .db "       FamiCom)                 "
  .db "                                "
  .db " 1985: NY e LA como Nintendo    "
  .db "       Entertainment System     "
  .db "                                "
  .db " 1986: EUA e partes da Europa   "
  .db "                                "
  .db " 1987: Austr",$0C,"lia, resto da      "
  .db "       Europa                   "
  .db "                                "
  .db " 1989: Coreia do Sul, como      "
  .db "       ",$8A,$8B,$20,$8C,$8D,$8E," (Hyundai Comboy)  "
  .db "                                "
  .db " 1993: Brasil, como Nintendinho "
  .db "                                "
  .db "                                "
  .db "                                "
  .db "                                "
  .db "                                "
  .db "                                "
  .db "                                "
  .db "                                "
  .db "                           1/12 "
  .db "                                "

slide2:
  .db $10,"     Tecnologia usada no      ",$11
  .db "     processador e mem",$13,"ria      "
  .db "                                "
  .db "                                "
  .db "                                "
  .db "                                "
  .db "                                "
  .db "                                "
  .db "                                "
  .db "                                "
  .db "                                "
  .db "                                "
  .db "                                "
  .db "                                "
  .db "          (slide 2)             "
  .db "                                "
  .db "                                "
  .db "                                "
  .db "                                "
  .db "                                "
  .db "                                "
  .db "                                "
  .db "                                "
  .db "                                "
  .db "                                "
  .db "                                "
  .db "                           2/12 "
  .db "                                "