;; TODO: Fix spritesheet! Accents and whatnot

slide1:
  .db $10,"      Ano de introdu",$87,$83,"o       ",$11
  .db "                                "
  .db " 1983: Jap",$C6,"o, como ",$40,$40,$40,$40,$40,$40,$40,$40,$40,$40,$40,"  "
  .db "       (Family Computer, FC ou  "
  .db "       FamiCom)                 "
  .db "                                "
  .db " 1985: NY e LA como Nintendo    "
  .db "       Entertainment System     "
  .db "                                "
  .db " 1986: EUA e partes da Europa   "
  .db "                                "
  .db " 1987: Austr",$A0,"lia, resto da      "
  .db "       Europa                   "
  .db "                                "
  .db " 1989: Coreia do Sul, como      "
  .db "       ",$40,$40," ",$40,$40,$40," (Hyundai Comboy)  "
  .db "                                "
  .db " 1993: Brasil, como Nintendinho "
  .db "                                "
  .db $FF,$12,$FE,"                             "
  .db "                                "
  .db "                                "
  .db "                                "
  .db "                                "
  .db "                                "
  .db "                                "
  .db "                           1/12 "
  .db "                                "

slide2:
  .db $10,"     Tecnologia usada no      ",$11
  .db "     processador e mem",$A2,"ria      "
  .db "                                "
  .db "                                "
  .db "                                "
  .db "                                "
  .db "                                "
  .db "                                "
  .db "                                "
  .db "                                "
  .db "                                "
  .db "                                "
  .db "                                "
  .db "                                "
  .db "          (slide 2)             "
  .db "                                "
  .db "                                "
  .db "                                "
  .db "                                "
  .db "                                "
  .db "                                "
  .db "                                "
  .db "                                "
  .db "                                "
  .db "                                "
  .db "                                "
  .db "                           2/12 "
  .db "                                "